package com.hospital.admissions.entity;

public enum OverrideReasonCode {
    ATTENDING_CLINICAL_REQUEST,
    WARD_STAFFING_LIMITATION,
    GOVERNMENT_SUBSIDY_CLASS_UPGRADE,
    EMERGENCY_PORTABLE_TELEMETRY_DEPLOYED,
    FAMILY_PROXIMITY_REQUEST
}
