spring:
  application:
    name: admissions
  profiles:
    active: prototype
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{activeUser:-ANON}] %logger{36} - %msg%n"
